### ISSUE TITLE
Help Needed

### ISSUE THREAD

**Issue by susheemmaurya** [oke-aditya/oke-aditya#1]
Hey Oke, 

You've got a great bunch of projects on your account all tracked via CI/CD. 
Could you tell me the resources you used to learn DevOps and Cloud. 

Thank you.

**Comment by oke-aditya** [comment]
Hello @susheemmaurya . I will suggest a few resources and github repositories that might be helpful.

[Automation Step by Step](https://www.youtube.com/channel/UCTt7pyY-o0eltq14glaG5dg) YouTube channel is great resource to get started. 

It has good playlists for docker, kubernetes, jenkins, PostMan etc.

Do check documentation of docker and kubernetes at their official websites !! 

They provide hands-on stuff as well.

Docker Official Website -> https://docs.docker.com/
Kubernetes official Website -> https://kubernetes.io/docs/tutorials/

For GitHub Actions, I could not find any great resources. 
But best available are documentation from GitHub and the template actions that they provide.
They are often almost complete.

You can try my [Python projects template](https://github.com/oke-aditya/template_python). 

It will set up CI CD for a Python project. 
I use it to start new projects with CI CD, tests and deployment.

For Cloud Computing AWS and GCP. 

I highly recommend [QwikLabs](https://www.qwiklabs.com/). 

They provide great hands-on labs. 

Also Coursera Courses for GCP and AWS are awesome !!

Some notes of these courses are available [here](https://github.com/oke-aditya/DevOps_Cloud)

Do let me know if you need more resources.

**Comment by susheemmaurya** [comment]
That's some generous documentation as a reply from you. 

Thank you @oke-aditya .
