### ISSUE TITLE
PyTorch developer slack

### ISSUE THREAD

**Issue by pmeier** [oke-aditya/oke-aditya#2]
Hey @oke-aditya. We wanted to invite you and few other core OSS contributors to the PyTorch developer Slack, so we can have easier discussions. I scrapped the emails for the others from our commit history, but you are using an anonymous one. If you are interested in joining the Slack workspace, please send me a contact email to `pmeier@quansight.com`.

**Comment by oke-aditya** [comment]
Just mailed you, :) Thanks a lot Philip

**Comment by pmeier** [comment]
Hey Aditya, just checking in: were you granted access?

**Comment by oke-aditya** [comment]
Nope Philip. Not yet.

**Comment by oke-aditya** [comment]
I had filled the form with gmail address as emailed. :( But no reply to it yet.

**Comment by pmeier** [comment]
I'll ping the people responsible

**Comment by oke-aditya** [comment]
Thanks a lot

**Comment by pmeier** [comment]
Just received confirmation that you were granted access. Please re-open this if you have trouble logging in. Otherwise, see you there :slightly_smiling_face:

**Comment by oke-aditya** [comment]
Yep see you there :)
